# Generated by Django 4.1 on 2022-09-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0003_alter_mywatchlistitem_watched'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mywatchlistitem',
            name='watched',
            field=models.CharField(max_length=50),
        ),
    ]
